### PR TITLE
Added firefox addon and updated readme

### PR DESCRIPTION
**Pull request by blankRSD**

### CODE REVIEW

**Review by thealphadollar — COMMENTED** [review]
Thanks for the PR. @blissmode can you please check this for working?

Fixes #1

**Comment by Krythz43** [comment]
@thealphadollar LGTM. Worked perfectly without issues.

**Comment by thealphadollar** [comment]
How did you create this? @blankRSD

**Comment by Krythz43** [comment]
Though I honestly recommend that the name requires some work :stuck_out_tongue:

**Comment by blankRSD** [comment]
The code remains the same just had to make a mozilla developer account. That's it. Good work from your side.

**Pull request merged**
